version: '3'
services:
  tfhe_experiment:
    network_mode: "host"
    restart: always
    build: .
    container_name: 'tfhe'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./:/root/home/
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    memswap_limit: 32G
